using UnityEngine;

namespace SpecialMoveCards
{
    /// <summary>Optional helper to log pocket contents for debugging.</summary>
    public class DebugPocketPrinter : MonoBehaviour
    {
        public PlayerPocket pocket;
        public float printEverySeconds = 5f;
        private float t;

        private void Reset()
        {
            pocket = GetComponent<PlayerPocket>();
        }

        private void Update()
        {
            t += Time.deltaTime;
            if (t >= printEverySeconds)
            {
                t = 0f;
                if (pocket == null) return;
                var snap = pocket.GetSnapshot();
                string a = snap[0] ? snap[0].moveName : "-";
                string b = snap[1] ? snap[1].moveName : "-";
                Debug.Log($"[Pocket] Slot1={a}, Slot2={b}, Count={pocket.Count}");
            }
        }
    }
}
